Dz4
dgmedvedev/MedvedevAndroidPvt pull request #5
Opened 2019-06-27 21:54 UTC by dgmedvedev

2019-06-27 21:56 UTC, stopstress approved these changes

2019-06-28 10:43 UTC, eugenia-shumeika approved these changes

2019-06-29 06:36 UTC, JerryMann approved these changes

2019-06-29 08:44 UTC, tim-teacher requested changes

2019-06-29 08:44 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz4/Dz4MyView.kt
> +        pathArrowH.lineTo(cx + 25, cy - radiusClock + 100)
что за магическое число 100? и тоже самое дальше по коду встречается. Выносите не понятные числа в константы с названием по которому можно понять что это. Если это размеры то они должны быть либо в dp либо рассчитывать из размеров экрана, что бы экран был адаптивным

2019-06-30 16:46 UTC, tim-teacher approved these changes

2019-07-06 15:29 UTC, merged