Dz5
dgmedvedev/MedvedevAndroidPvt pull request #6
Opened 2019-06-28 10:18 UTC by dgmedvedev

https://apf.mail.ru/cgi-bin/readmsg?id=15617170181954912192;0;1&af_preview=1&exif=1

2019-06-28 10:46 UTC, eugenia-shumeika approved these changes

2019-06-28 15:46 UTC, 3RUN approved these changes

2019-06-28 20:08 UTC, stopstress approved these changes

2019-06-29 08:47 UTC, tim-teacher requested changes

2019-06-29 08:47 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz5/Dz5MenuActivity.kt
> +class Dz5MenuActivity : Activity() {
так а где мню где можно все ДЗ стартануть? вижу только возможность стартануть ДЗ 0 и ДЗ 1

2019-06-29 08:47 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz5/part1/Dz5Activity1.kt
> +class Dz5Activity1 : Activity() {
Dz5Activity1 -> Dz5Activity

2019-06-29 08:47 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz5/part1/MyViewDz5.kt
> +class MyViewDz5 : View {
MyViewDz5 -> Dz5MyView

2019-06-29 08:47 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz5/part1/MyViewDz5.kt
> +    constructor(context: Context?) : super(context)
конструкторы должны быть в начале файла после переменных

2019-06-29 08:47 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz5/part1/MyViewDz5.kt
> +        radiusCircleOnLine = radius * 0.05f
снова магические числа, в предыдущем ДЗ уже написал по этому поводу

2019-06-29 17:57 UTC, dgmedvedev commented on app/src/main/java/by/itacademy/pvt/dz5/Dz5MenuActivity.kt
> +class Dz5MenuActivity : Activity() {
у Dz5MenuActivity есть две кнопки: part1 (с переходом на Dz5Activity1 - диаграмма) и part2 (с переходом на Dz5Activity2 - сова). так же и с Dz2

2019-06-30 00:16 UTC, stopstress approved these changes

2019-06-30 16:47 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz5/Dz5MenuActivity.kt
> +class Dz5MenuActivity : Activity() {
ок

2019-06-30 16:47 UTC, tim-teacher approved these changes

2019-07-07 09:23 UTC, merged