Dz6
dgmedvedev/MedvedevAndroidPvt pull request #7
Opened 2019-07-06 15:46 UTC by dgmedvedev

![Screenshot_20190706-174914](https://user-images.githubusercontent.com/42978913/60758270-2d3dd200-a01e-11e9-9700-5fe028245ae2.png)
![Screenshot_20190706-175224](https://user-images.githubusercontent.com/42978913/60758271-3464e000-a01e-11e9-8605-2a0a168dd3f6.png)
![Screenshot_20190706-175231](https://user-images.githubusercontent.com/42978913/60758276-3c248480-a01e-11e9-938c-15652efdaa26.png)

2019-07-06 17:04 UTC, 3RUN approved these changes

2019-07-08 07:03 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/dz6/Dz6StudentEditActivity.kt
> +            val name = findViewById<EditText>(R.id.nameEditText).text.toString()
FindViewById не должно быть в кликЛиснере

2019-07-08 07:05 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/dz6/Dz6StudentEditActivity.kt
> +            val url = "https://clck.ru/Gx4Nd" // для тестирования приложения,
Если для тестирования, лучше обернуть в if (BuildConfig.DEBUG)

2019-07-08 07:10 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/dz6/Dz6StudentEditActivity.kt
> +                    findViewById<EditText>(R.id.ageEditText).text.toString().toInt()
А если поле с возрастом пустое?

2019-07-08 07:17 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/dz6/Dz6StudentEditActivity.kt
> +            if (idStudent != -1L) {
А поля эдитТекстов заполнить данными студента?

2019-07-08 12:35 UTC, dgmedvedev commented on app/src/main/java/by/itacademy/pvt/dz6/Dz6StudentEditActivity.kt
> +                    findViewById<EditText>(R.id.ageEditText).text.toString().toInt()
если пустое или введены не цифры то исключение NumberFormatException
catch (nfe: NumberFormatException) {
            Toast.makeText(
                this,
                resources.getText(R.string.enter_age),
                Toast.LENGTH_SHORT
            ).show()
        }

2019-07-08 12:53 UTC, tim-teacher requested changes

2019-07-08 12:53 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz6/Dz6StudentDetailsActivity.kt
> +        user?.let {
так а если нет студента? пользователь нажал на студента, сюда прилетел id, но по этому id ничего не нашли? будет висеть пустой экран?

2019-07-08 12:53 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz6/Dz6StudentEditActivity.kt
> +            val name = findViewById<EditText>(R.id.nameEditText).text.toString()
возможно сделано из расчета что если юзер не нажимал на save то FindViewById и не будет вызываться, и учитывая что после save мы возвращаемся на другой экран в целом еще нормально.
Но вообще лучше убрать, просто даже код будет попроще

2019-07-08 12:53 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz6/Dz6StudentEditActivity.kt
> +            val url = "https://clck.ru/Gx4Nd" // для тестирования приложения,
да, тестовые данные не стоит просто так оставлять

2019-07-08 12:53 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz6/Dz6StudentEditActivity.kt
> +            if (idStudent != -1L) {
ага, выже тестите хотя бы перед тем как выслать ДЗ

2019-07-08 12:53 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz6/Dz6StudentEditActivity.kt
> +                    findViewById<EditText>(R.id.ageEditText).text.toString().toInt()
нужно проверки на все поля добавить, вы же не знаете что там вообще юзер может умудриться ввести

2019-07-08 14:33 UTC, dgmedvedev commented on app/src/main/java/by/itacademy/pvt/dz6/Dz6StudentEditActivity.kt
> +            if (idStudent != -1L) {
в синглтоне заполнил

2019-07-08 14:34 UTC, dgmedvedev commented on app/src/main/java/by/itacademy/pvt/dz6/Dz6StudentEditActivity.kt
> +            val url = "https://clck.ru/Gx4Nd" // для тестирования приложения,
ок, обернул

2019-07-09 18:28 UTC, tim-teacher approved these changes

2019-07-09 20:15 UTC, eugenia-shumeika approved these changes

2019-07-09 20:45 UTC, merged