Dz8
dgmedvedev/MedvedevAndroidPvt pull request #8
Opened 2019-07-14 17:35 UTC by dgmedvedev

2019-07-14 20:10 UTC, eugenia-shumeiko commented on app/src/main/java/by/itacademy/pvt/dz8/AppPrefManager.kt
> +import by.itacademy.pvt.dz8.Dz8StudentListFragment.Companion.SHARED_PREFS_NAME
Эти константы лучше тут и хранить, а не во фрагменте

2019-07-14 22:28 UTC, tim-teacher requested changes
Мелочи конечно, но нужно поправить

2019-07-14 22:28 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz8/AppPrefManager.kt
> +import by.itacademy.pvt.dz8.Dz8StudentListFragment.Companion.SHARED_PREFS_NAME
да, крайне странно название файла хранить в фрагменте хотя логика тут, идея AppPrefManager как раз в том что бы фрагмент не знал где конкретно мы храним данные, в шаред преференсах, базе данных или еще гдето

2019-07-14 22:28 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz8/Dz8FragmentActivity.kt
> +        var isPhone = true
эм а зачем это в companion object закидывать? Все же разрешение экрана это зависимая от экрана величина, не стоит загонять это в companion object, это же фактически статик

2019-07-14 22:28 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz8/Dz8FragmentActivity.kt
> +        if (screenSize >= screenDiagonal) isPhone = false
ухх, посмотрел класс ScreenSizeCalculator, мне кажется это очень шадкое решение, в плане есть большой риск что гдето заработает не так как необходимо. Я бы все рекомендовал взять текущую ориентацию из праметра resources.configuration.orientation;

2019-07-14 22:28 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz8/Dz8FragmentActivity.kt
> +    private fun choiceContainer(fragment: Fragment) {
choice -> choose, будет получше

2019-07-15 09:26 UTC, dgmedvedev commented on app/src/main/java/by/itacademy/pvt/dz8/AppPrefManager.kt
> +import by.itacademy.pvt.dz8.Dz8StudentListFragment.Companion.SHARED_PREFS_NAME
исправил

2019-07-15 09:30 UTC, dgmedvedev commented on app/src/main/java/by/itacademy/pvt/dz8/Dz8FragmentActivity.kt
> +        var isPhone = true
использовал ее в Dz8StudentDetailsFragment. исправил

2019-07-15 09:31 UTC, dgmedvedev commented on app/src/main/java/by/itacademy/pvt/dz8/Dz8FragmentActivity.kt
> +        if (screenSize >= screenDiagonal) isPhone = false
исправил

2019-07-15 09:31 UTC, dgmedvedev commented on app/src/main/java/by/itacademy/pvt/dz8/Dz8FragmentActivity.kt
> +    private fun choiceContainer(fragment: Fragment) {
исправил

2019-07-15 09:35 UTC, 3RUN approved these changes

2019-07-15 10:46 UTC, tim-teacher approved these changes

2019-07-15 10:47 UTC, eugenia-shumeika approved these changes

2019-07-17 15:50 UTC, merged