Dz9
dgmedvedev/MedvedevAndroidPvt pull request #9
Opened 2019-07-19 21:04 UTC by dgmedvedev

Ссылка на apk-файл:
https://my-files.ru/oav7kn

2019-07-21 22:24 UTC, AndreyKa986 approved these changes

2019-07-25 21:58 UTC, tim-teacher requested changes

2019-07-25 21:58 UTC, jushlwest commented on app/src/debug/res/values/google_maps_api.xml
> +    C4:27:19:51:2B:D6:96:CF:1F:64:C9:2E:E7:26:5E:9A:29:D4:87:61
удалите эти комменты, не нужно светить этими данными)

2019-07-25 21:58 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz9/CarRepositoryRemote.kt
> +                listener.onSuccess(response.body()!!.poiList)
response.body()?.let{
       listener.onSuccess(it.poiList)
} ?: listener.onError(Exception("Body is empty"))
так будет лучше

2019-07-25 21:58 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz9/Dz9Activity.kt
> +        map.isMyLocationEnabled = true
а что если ответ прийдет быстрее чем onMapReady() сработает? Необходимо этот вариант тоже предусмотреть.

Также:
private lateinit var map: GoogleMap
private lateinit var mapView: MapView
оба этих параметра потенциально могут быть нулевыми если с картой что то случится, поэтому лучше их делать не lateinit а просто нелевыми. Ну и по ходу дела это проверять проверять.

2019-07-25 21:58 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz9/Dz9Activity.kt
> +        map.isMyLocationEnabled = true
а что если ответ прийдет быстрее чем onMapReady() сработает? Необходимо этот вариант тоже предусмотреть.

Также:
private lateinit var map: GoogleMap
private lateinit var mapView: MapView
оба этих параметра потенциально могут быть нулевыми если с картой что то случится, поэтому лучше их делать не lateinit а просто нелевыми. Ну и по ходу дела это проверять проверять.

2019-07-25 21:58 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz9/Dz9Activity.kt
> +                    .rotation(it.heading!!.toFloat())
что за !!, а если этих данные реально нет? вы же не можете доверять серверу на 100%,  лишний if не помешает:)

2019-07-25 21:58 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz9/Dz9Activity.kt
> +                resources.displayMetrics.widthPixels / 5
не понятно что за 5? Либо в константы вынесите либо комментов пометься что это такое.

2019-07-25 21:58 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz9/Dz9Activity.kt
> +                    BitmapFactory.decodeResource(resources, R.drawable.ic_taxi)
Чтение из ресурсов и декодирование картинки дорогая операция, а так как картинки у вас очень часто повторяются есть смысле сделать это один раз на старте приложение и сохранить в переменну.
Можно конструкцию lazy тут заиспользовать.

2019-07-25 21:58 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz9/Dz9CarListFragment.kt
> +    private lateinit var adapter: Dz9Adapter
если результат будет не успешный то ваш late init так и останется неинициализированным, лучше все же тутже создать адаптер и просто методом добавлять данные

2019-07-26 17:25 UTC, dgmedvedev commented on app/src/main/java/by/itacademy/pvt/dz9/Dz9CarListFragment.kt
> +    private lateinit var adapter: Dz9Adapter
все исправил

2019-07-27 20:18 UTC, tim-teacher approved these changes

2019-07-27 20:18 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz9/Dz9Activity.kt
> +        mapView?.onStart() ?: onError(Exception(mapViewIsEmpty))
не совсем понятно зачем вам onError(Exception(mapViewIsEmpty)), ну нуливая и хорошо, если нулевая значит ничего и не надо делать :)

2019-07-28 07:16 UTC, merged